export const products = [
    { id: 1, 
    title: 'Music System Speaker', 
    amount: '80,000', 
    image: '/images/img/1.png', 
    qty: 1},
    { id: 2, 
    title: 'Portable Neck Fan', 
    amount: '50,000', 
    image: '/images/img/2.png', 
    qty: 1},
    { id: 3, 
    title: 'Dynamic Sound', 
    amount: '20,000', 
    image: '/images/img/3.png', 
    qty: 1},
    { id: 4, 
    title: 'Advanced Heart Rate Monitor', 
    amount: '100,000', 
    image: '/images/img/4.png', 
    qty: 1},
    { id: 5, 
    title: 'Heart Rate Monitor', 
    amount: '100,000', 
    image: '/images/img/5.png', 
    qty: 1},
    { id: 6, 
    title: 'Professional Skipping Rope', 
    amount: '30,000', 
    image: '/images/img/6.png', 
    qty: 1},
    { id: 7, 
    title: 'Ultimate Electronics Cleaning Kit', 
    amount: '8,000', 
    image: '/images/img/7.png', 
    qty: 1},
    { id: 8, 
    title: 'Foldable Aluminum Laptop Stand', 
    amount: '80,000', 
    image: '/images/img/8.png', 
    qty: 1},
    { id: 9, 
    title: 'Ultra-Thin Transparent Hard Case', 
    amount: '15,000', 
    image: '/images/img/9.png', 
    qty: 1},
    { id: 10, 
    title: 'Dynamic Sports In-Ear Headphones', 
    amount: '80,000', 
    image: '/images/img/10.png', 
    qty: 1},
    { id: 11, 
    title: 'Smart Watch', 
    amount: '30,000', 
    image: '/images/img/11.png', 
    qty: 1},
    { id: 12, 
    title: 'Yoga Form Roller', 
    amount: '20,000', 
    image: '/images/img/12.png', 
    qty: 1},
    { id: 13, 
    title: 'Digital Kitchen Coffee Scale', 
    amount: '100,000', 
    image: '/images/img/13.png', 
    qty: 1},
    { id: 14, 
    title: 'Magnetic Kitchen Timer', 
    amount: '50,000', 
    image: '/images/img/14.png', 
    qty: 1},
    { id: 15, 
    title: 'Magnetic Kitchen Timer', 
    amount: '30,000', 
    image: '/images/img/15.png', 
    qty: 1},
  ];